#pragma once

#include <regex>
#include <string>
#include <vector>
using namespace std;


class BasicRules
{
protected:
	regex re;
	string RuleName;
public:
	BasicRules(const string& re, const string& RuleName);
	bool isMatch(const string& input) const ;
};

const vector<BasicRules> AllBasicRules({
    BasicRules(R"(^[0-9]$)", "Digit"),
    BasicRules(R"(^[1-9]$)", "NonzeroDigit"),
    BasicRules(R"(^[0-7]$)", "OctalDigit"),
    BasicRules(R"(^[0-9a-fA-F]$)", "HexadecimalDigit"),
    BasicRules(R"(^[0-1]$)", "BinaryDigit"),
    BasicRules(R"(^[1-9]$)", "NoneZeroDigit"),
    BasicRules(R"(^[ \t\r\n]+$)", "WhiteSpace"),
    BasicRules(R"(^[\r\n]+$)", "Newline"),
    BasicRules(R"(^[a-zA-Z]$)", "Chars"),
    BasicRules(R"(^[A-Z]$)", "UpChars"),
    BasicRules(R"(^[a-z]$)", "LowerChars"),
    BasicRules(R"(^->$)", "Arrow"),
    BasicRules(R"(^\+\+$)", "Inc"),
    BasicRules(R"(^--$)", "Dec"),
    BasicRules(R"(^<<=$)", "LShiftAssign"),
    BasicRules(R"(^>>=$)", "RShiftAssign"),
    BasicRules(R"(^\+=$)", "PlusAssign"),
    BasicRules(R"(^-=$)", "MinusAssign"),
    BasicRules(R"(^\*=$)", "StarAssign"),
    BasicRules(R"(^/=$)", "SlashAssign"),
    BasicRules(R"(^%=$)", "PercentAssign"),
    BasicRules(R"(^&=$)", "AmpAssign"),
    BasicRules(R"(^\|=$)", "BitorAssign"),
    BasicRules(R"(^\^=$)", "CaretAssign"),
    BasicRules(R"(^==$)", "Eq"),
    BasicRules(R"(^!=$)", "Ne"),
    BasicRules(R"(^<=$)", "Le"),
    BasicRules(R"(^>=$)", "Ge"),
    BasicRules(R"(^<<$)", "LShift"),
    BasicRules(R"(^>>$)", "RShift"),
    BasicRules(R"(^&&$)", "And"),
    BasicRules(R"(^\|\|$)", "Or"),
    BasicRules(R"(^\($)", "LParen"),
    BasicRules(R"(^\)$)", "RParen"),
    BasicRules(R"(^\[$)", "LBrack"),
    BasicRules(R"(^\]$)", "RBrack"),
    BasicRules(R"(^\{$)", "LBrace"),
    BasicRules(R"(^\}$)", "RBrace"),
    BasicRules(R"(^;$)", "Semi"),
    BasicRules(R"(^,$)", "Comma"),
    BasicRules(R"(^\.$)", "Dot"),
    BasicRules(R"(^\+$)", "Pos"),
    BasicRules(R"(^-$)", "Neg"),
    BasicRules(R"(^\*$)", "Star"),
    BasicRules(R"(^/$)", "Slash"),
    BasicRules(R"(^%$)", "Percent"),
    BasicRules(R"(^&$)", "Amp"),
    BasicRules(R"(^\|$)", "Bitor"),
    BasicRules(R"(^\^$)", "Caret"),
    BasicRules(R"(^~$)", "Tilde"),
    BasicRules(R"(^!$)", "Exclam"),
    BasicRules(R"(^\?$)", "Question"),
    BasicRules(R"(^:$)", "Colon"),
    BasicRules(R"(^=$)", "Assign"),
    BasicRules(R"(^<$)", "Lt"),
    BasicRules(R"(^>$)", "Gt"),
    BasicRules(R"(^_$)", "Underscore"),
    BasicRules(R"(^#$)", "Hash"),
    BasicRules(R"(^'$)", "SingleQuote"),
    BasicRules(R"(^\"$)", "DoubleQuote"),
    BasicRules(R"(^.$)", "AllChar"),
    BasicRules(R"(^auto$)", "Auto"),
    BasicRules(R"(^break$)", "Break"),
    BasicRules(R"(^case$)", "Case"),
    BasicRules(R"(^char$)", "Char"),
    BasicRules(R"(^const$)", "Const"),
    BasicRules(R"(^continue$)", "Continue"),
    BasicRules(R"(^default$)", "Default"),
    BasicRules(R"(^do$)", "Do"),
    BasicRules(R"(^double$)", "Double"),
    BasicRules(R"(^else$)", "Else"),
    BasicRules(R"(^enum$)", "Enum"),
    BasicRules(R"(^extern$)", "Extern"),
    BasicRules(R"(^float$)", "Float"),
    BasicRules(R"(^for$)", "For"),
    BasicRules(R"(^goto$)", "Goto"),
    BasicRules(R"(^if$)", "If"),
    BasicRules(R"(^int$)", "Int"),
    BasicRules(R"(^long$)", "Long"),
    BasicRules(R"(^register$)", "Register"),
    BasicRules(R"(^return$)", "Return"),
    BasicRules(R"(^short$)", "Short"),
    BasicRules(R"(^signed$)", "Signed"),
    BasicRules(R"(^sizeof$)", "Sizeof"),
    BasicRules(R"(^static$)", "Static"),
    BasicRules(R"(^struct$)", "Struct"),
    BasicRules(R"(^switch$)", "Switch"),
    BasicRules(R"(^typedef$)", "Typedef"),
    BasicRules(R"(^union$)", "Union"),
    BasicRules(R"(^unsigned$)", "Unsigned"),
    BasicRules(R"(^void$)", "Void"),
    BasicRules(R"(^volatile$)", "Volatile"),
    BasicRules(R"(^while$)", "While"),
    BasicRules(R"(^inline$)", "Inline"),
    BasicRules(R"(^restrict$)", "Restrict"),
    BasicRules(R"(^_Bool$)", "UBool"),
    BasicRules(R"(^_Complex$)", "UComplex"),
    BasicRules(R"(^_Imaginary$)", "UImaginary"),
    BasicRules(R"(^_Alignas$)", "UAlignas"),
    BasicRules(R"(^_Alignof$)", "UAlignof"),
    BasicRules(R"(^_Atomic$)", "UAtomic"),
    BasicRules(R"(^_Generic$)", "UGeneric"),
    BasicRules(R"(^_Noreturn$)", "UNoreturn"),
    BasicRules(R"(^_Static_assert$)", "UStaticAssert"),
    BasicRules(R"(^_Thread_local$)", "UThreadLocal"),
    BasicRules(R"(^alignas$)", "Alignas"),
    BasicRules(R"(^alignof$)", "Alignof"),
    BasicRules(R"(^bool$)", "Bool"),
    BasicRules(R"(^static_assert$)", "StaticAssert"),
    BasicRules(R"(^thread_local$)", "ThreadLocal"),
    BasicRules(R"(^_BitInt$)", "UBitInt"),
    BasicRules(R"(^_Decimal128$)", "UDecimal128"),
    BasicRules(R"(^_Decimal32$)", "UDecimal32"),
    BasicRules(R"(^_Decimal64$)", "UDecimal64"),
    BasicRules(R"(^constexpr$)", "Constexpr"),
    BasicRules(R"(^define$)", "Define"),
    BasicRules(R"(^ifdef$)", "IfDef"),
    BasicRules(R"(^ifndef$)", "IfNDef"),
    BasicRules(R"(^elif$)", "Elif"),
    BasicRules(R"(^endif$)", "EndIf"),
    BasicRules(R"(^include$)", "Include"),
    BasicRules(R"(^line$)", "Line"),
    BasicRules(R"(^error$)", "Error"),
    BasicRules(R"(^pragma$)", "Pragma"),
    BasicRules(R"(^undef$)", "Undef"),
    BasicRules(R"(^_Pragma$)", "UPragma"),
    BasicRules(R"(^asm$)", "Asm"),
    BasicRules(R"(^fortran$)", "Fortra")
    });
