#line 2 "lex.yy.c"

#line 4 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 119
#define YY_END_OF_BUFFER 120
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[520] =
    {   0,
        0,    0,  120,  118,  117,  117,   64,   72,   70,   60,
       61,   71,   48,   49,   58,   56,   54,   57,   55,   59,
        6,    6,   66,   73,   68,   67,   69,   65,  116,  116,
       52,   53,   63,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,   50,   62,
       51,   41,    0,    3,    0,   36,   46,   37,    0,    0,
       34,   28,   32,   29,   33,   27,    5,    0,    1,   35,
        5,    6,    0,    0,    0,    6,    6,    0,    6,    6,
       44,   42,   40,   43,   45,  116,    0,    0,   39,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,

      116,  116,  116,  116,  116,   11,  116,  116,  116,  116,
      116,   14,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,   38,   47,    0,    0,    0,    0,
        0,    4,    0,    0,    0,    0,    0,    5,    0,    0,
        1,    1,    6,    6,    6,    6,    0,    5,    6,    6,
        6,    6,    0,    6,   30,   31,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,   23,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,   13,  116,
       85,  116,  116,  116,  116,  116,  116,  116,  116,  116,

      116,  116,  116,  116,  116,  116,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    5,    2,    0,    6,    6,
        6,    6,    5,    6,    6,    0,    0,    6,    0,    6,
        6,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,   76,  116,    8,   83,  116,
      116,  116,  116,   12,   97,  116,  116,  116,  116,   86,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,   82,  116,  116,    0,    0,    0,    0,    0,    0,
        0,    0,    6,    6,    6,    6,    0,    5,    6,    6,

      116,  116,   89,  116,  116,  116,  116,  116,  116,   25,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,    7,   98,  116,  116,  116,  116,
       87,  116,  116,  116,  116,  116,   84,  116,  116,  116,
      116,  116,   96,  116,  116,   17,    0,    0,    0,    0,
        6,    5,    6,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
       92,  116,  116,  116,  116,  116,  116,  116,   88,   78,
      116,  103,  116,  116,   15,   74,   77,   95,   16,  116,
      116,  116,    0,    0,    0,    0,  116,  102,  116,  116,

      116,  116,  116,  116,   26,  116,  116,  107,  116,  116,
      116,  116,  116,   93,   94,  116,  116,  116,  116,  116,
      116,   10,   24,  116,  116,   81,  116,  116,    0,    0,
       18,   90,   19,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,    9,
       79,   99,   75,  100,    0,    0,  116,  105,  116,  116,
      116,  116,  108,  116,  116,  116,  116,  106,  116,  116,
      116,  116,    0,    0,   91,  116,  116,  116,  116,  114,
      116,  109,  104,  110,  112,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,

      116,  111,  101,  116,   80,  115,  116,  116,  113,   20,
      116,  116,  116,  116,  116,   21,  116,   22,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   22,   22,   22,   22,   23,   24,   25,   26,   27,
       28,   29,   30,    1,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   38,   38,   40,   38,   41,   38,   42,
       38,   38,   43,   44,   45,   38,   38,   46,   38,   38,
       47,   48,   49,   50,   51,    1,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   38,   61,   62,   63,   64,
       65,   66,   38,   67,   68,   69,   70,   71,   72,   73,
       74,   38,   75,   76,   77,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[78] =
    {   0,
        1,    1,    2,    2,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        6,    6,    7,    7,    1,    1,    1,    1,    1,    3,
        7,    7,    7,    7,    7,    7,    8,    8,    8,    8,
        8,    8,    8,    8,    9,    8,    1,    3,    1,    1,
        8,    6,    6,    7,    7,    7,    6,    8,    8,    8,
        8,    8,    8,    9,    8,    8,    9,    8,    9,    9,
        9,    8,    9,    8,    1,    1,    1
    } ;

static const flex_int16_t yy_base[552] =
    {   0,
        0,    0,  852,  853,  853,  853,  823,   72,  853,  822,
       70,  801,  853,  853,  820,   66,  853,   67,   65,   79,
      104,  161,  853,  853,   54,  819,   62,  853,    0,   93,
      853,  853,  818,  156,   32,  778,   49,   48,   67,   44,
       48,  779,  787,   73,  768,  112,  776,  781,  853,   65,
      853,  853,  104,  853,  229,  853,  853,  853,  105,  149,
      853,  853,  853,  853,  853,  853,  284,  826,  790,  853,
        0,  330,  191,   97,  222,  103,   94,  820,   85,    0,
      808,  853,  853,  853,  807,    0,  113,  786,  853,   89,
      768,  767,  775,  767,  764,  759,  768,  200,  763,  756,

      768,  755,  770,  757,  763,  749,  750,  747,  747,  750,
      747,    0,  103,  749,  134,  747,  753,  112,  750,  743,
      802,   78,  156,  747,  853,  853,  803,  269,    0,    0,
        0,  853,  291,    0,    0,    0,  307,  853,  792,  141,
      756,  217,  164,  165,  217,  143,  313,  336,  213,  853,
      763,  740,    0,  321,  853,  853,  741,  735,  734,  735,
      733,  744,  728,  742,  726,  122,  722,  175,  735,  717,
      737,  724,  767,  717,  166,  205,    0,  720,  732,  727,
      715,  160,  729,  727,  723,  715,  721,  724,  706,  714,
        0,  715,  712,  702,  700,  702,  704,  698,  696,  696,

      708,  698,  702,  706,  708,  697,  358,    0,    0,  401,
      391,    0,    0,  449,  395,  455,  853,  755,  222,  853,
      717,  694,  853,  853,  853,  231,  243,  303,  424,  232,
      326,  697,  691,  691,  686,  695,  692,  693,  679,  691,
      683,  676,  684,  687,  675,  687,  671,  671,  676,  716,
      681,  675,  668,  679,  670,    0,  670,    0,    0,  661,
      669,  658,  665,    0,    0,  659,  656,  657,  659,    0,
      654,  654,  653,  650,  662,  657,  662,  661,  659,  649,
      654,    0,  642,  654,  218,    0,    0,    0,  127,    0,
        0,    0,  853,  853,  297,  853,  407,  499,  669,  646,

      643,  646,    0,  643,  637,  643,  633,  641,  648,  648,
      631,  635,  642,  641,  632,  637,  623,  631,  667,  635,
      620,  631,  617,  633,    0,    0,  620,  621,  626,  617,
        0,  628,  623,  609,  617,  612,    0,  620,  620,  604,
      613,  615,    0,  606,  609,    0,    0,    0,    0,    0,
      853,  853,  853,  616,  613,  610,  605,  600,  593,  608,
      546,  538,  528,  517,  512,  520,  495,  496,  505,  494,
      314,  505,  501,  489,  488,  483,  481,  481,    0,    0,
      485,    0,  492,  493,    0,    0,    0,    0,    0,  489,
      489,  482,    0,  270,    0,  268,  475,    0,  469,  487,

      488,  471,  486,  485,    0,  481,  473,    0,  470,  465,
      462,  477,  472,    0,    0,  465,  474,  468,  457,  456,
      459,    0,    0,  447,  444,    0,  456,  454,    0,    0,
        0,    0,    0,  442,  444,  455,  438,  429,  434,  434,
      438,  433,  430,  439,  427,  426,  436,  432,  405,    0,
        0,    0,    0,    0,    0,    0,  392,    0,  397,  399,
      394,  411,    0,  407,  395,  390,  400,    0,  388,  391,
      389,  353,    0,    0,    0,  340,  351,  348,  297,    0,
      339,    0,    0,    0,    0,  340,  348,  341,  343,  343,
      333,  337,  334,  322,  331,  314,  283,  293,  268,  271,

      264,    0,    0,  245,    0,    0,  227,  232,    0,    0,
      224,  197,  129,  128,  102,    0,   54,    0,  853,  561,
      570,  574,  581,  590,  599,  604,  606,  608,  610,  612,
      614,  616,  618,  620,  622,  624,  626,  628,  630,  632,
      634,  636,  638,  640,  642,  644,  646,  648,  650,  652,
      654
    } ;

static const flex_int16_t yy_def[552] =
    {   0,
      519,    1,  519,  519,  519,  519,  519,  520,  519,  519,
      519,  521,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  522,  522,
      519,  519,  519,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  519,  519,
      519,  519,  520,  519,  519,  519,  519,  519,  521,  523,
      519,  519,  519,  519,  519,  519,  519,  524,  525,  519,
       67,  519,  519,  519,  519,  519,  519,  526,  519,   22,
      519,  519,  519,  519,  519,  522,  520,  521,  519,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  519,  519,  519,  520,  527,  528,
      529,  519,  521,  530,  531,  532,  519,  519,  524,  524,
      525,  525,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  533,  526,  519,  519,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  520,  534,  535,  520,
      521,  536,  537,  521,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  533,  533,  519,  519,  519,
      519,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  520,  538,  539,  210,  521,  540,
      541,  214,  519,  519,  519,  519,  519,  519,  519,  519,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  542,  543,  544,  545,
      519,  519,  519,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  546,  520,  547,  521,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  548,  549,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  550,  551,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  543,  545,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,    0,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519
    } ;

static const flex_int16_t yy_nxt[931] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   23,   24,   25,   26,   27,   28,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   30,
       29,   29,   29,   29,   30,   29,   31,    4,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   29,   29,   41,
       29,   42,   29,   29,   29,   29,   43,   44,   45,   46,
       47,   48,   29,   29,   49,   50,   51,   54,   57,   62,
       81,   82,   64,   67,   67,   67,   67,   67,   67,   84,
       85,   68,  125,   63,   65,   66,   69,   58,   87,   99,

      102,  100,   88,  105,  112,  110,   70,  103,  111,   54,
      518,  113,  106,  104,  132,  146,  146,   87,   54,   55,
       71,   88,   72,   72,   72,   72,   73,   73,  107,  150,
      108,  116,  117,  151,  121,   74,  132,  202,   75,  109,
      126,  118,  149,   76,  119,  203,  149,  150,   77,   78,
      157,   55,   60,  140,  150,  152,   74,  158,  217,   75,
       55,  146,  146,  198,  190,   79,  517,  133,  133,  133,
      133,  191,  150,   77,   60,  122,   78,   71,  199,   80,
       80,   80,   80,   80,   80,  516,   90,   91,   92,  241,
      242,  193,   93,  134,   94,   75,   95,  515,   96,   97,

       76,  194,  195,  219,  221,   77,   98,   71,  220,   73,
       73,   73,   73,   73,   73,  204,   75,  205,  135,  141,
      218,  136,   79,   54,  252,   75,  222,  260,  261,  244,
       77,   53,  127,  220,   53,  147,  245,  147,   53,  253,
      148,  148,  148,  148,  148,  148,   75,  128,  128,  128,
      128,  166,  167,  168,  169,  170,  171,  224,   53,  172,
      254,  220,  173,  514,  142,   55,  293,  174,  175,  255,
      176,  299,  229,  129,   54,   54,   53,  132,  219,  513,
       53,   53,  224,  512,  229,   53,  220,  207,  207,  207,
      207,  293,   53,  300,  511,   53,  229,   53,  130,   53,

      132,  131,   67,   67,   67,   67,   67,   67,  229,  211,
      211,  211,  211,  510,  509,   60,   55,   55,  137,  138,
      215,  508,  215,  138,  507,  216,  216,  216,  216,  216,
      216,  148,  148,  148,  148,  148,  148,  227,   60,  137,
      138,  351,  295,  506,  505,  138,   71,  296,   72,   72,
       72,   72,   73,   73,  148,  148,  148,  148,  148,  148,
      228,  491,  229,   54,   75,  230,  351,  492,  414,  143,
      296,  223,  296,  415,  144,  223,  285,  285,  285,  285,
      504,  503,  231,  502,  501,   75,  229,  295,  500,  499,
      230,  145,  223,  498,  497,  296,  496,  223,  495,  144,

      132,  494,  493,  490,  489,   55,   54,  488,  487,  289,
      289,  289,  289,  216,  216,  216,  216,  216,  216,  288,
      288,  288,  288,  288,  288,  298,  298,  298,  298,  298,
      298,  288,  288,  288,  288,  288,  288,  297,   60,  297,
      486,  485,  298,  298,  298,  298,  298,  298,   55,  484,
      483,  482,  288,  288,  288,  288,  288,  288,  132,  481,
      480,  479,  478,  477,  476,  475,  472,  292,  292,  292,
      292,  292,  292,  216,  216,  216,  216,  216,  216,  292,
      292,  292,  292,  292,  292,  471,  470,  469,  468,  467,
      138,  466,  465,  464,  138,  463,   60,  462,  461,  460,

      292,  292,  292,  292,  292,  292,  459,  458,  457,  454,
      453,  138,  452,  451,  450,  449,  138,  298,  298,  298,
      298,  298,  298,  448,  447,  446,  445,  444,  443,  442,
      441,  440,  439,  438,  352,  437,  436,  435,  352,  434,
      433,  432,  431,  428,  427,  426,  425,  424,  423,  422,
      421,  420,  419,  418,  417,  352,  416,  413,  412,  411,
      352,   53,  410,   53,   53,   53,   53,   53,   53,   53,
       59,  409,   59,  408,   59,   59,   59,   59,   59,   86,
       86,   86,   86,   59,   59,  407,   59,  406,  405,   59,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  141,

      404,  141,  141,  141,  141,  141,  141,  141,  154,  154,
      154,  208,  208,  209,  209,  210,  210,  212,  212,  213,
      213,  214,  214,  226,  226,  286,  286,  287,  287,  290,
      290,  291,  291,  347,  347,  348,  348,  349,  349,  350,
      350,  393,  393,  394,  394,  395,  395,  396,  396,  429,
      429,  430,  430,  455,  455,  456,  456,  473,  473,  474,
      474,  403,  402,  401,  400,  399,  398,  397,  392,  391,
      390,  389,  388,  387,  386,  385,  384,  383,  382,  381,
      380,  379,  378,  377,  376,  375,  374,  373,  372,  371,
      370,  369,  368,  367,  366,  365,  364,  363,  362,  361,

      360,  359,  358,  357,  356,  355,  354,  353,  353,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      305,  304,  303,  302,  301,  294,  294,  141,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  259,  258,  257,  256,  251,  250,  249,  248,  247,
      246,  243,  240,  239,  238,  237,  236,  235,  234,  233,

      232,  225,  225,  142,  140,   53,  206,   87,  201,  200,
      197,  196,  192,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  177,  165,  164,  163,  162,
      161,  160,  159,   60,  156,  155,  153,  142,  140,  124,
      123,  120,  115,  114,  101,   89,   83,   61,   60,   56,
       52,  519,    3,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519
    } ;

static const flex_int16_t yy_chk[931] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    8,   11,   16,
       25,   25,   18,   19,   19,   19,   19,   19,   19,   27,
       27,   20,   50,   16,   18,   18,   20,   11,   30,   35,

       37,   35,   30,   38,   41,   40,   20,   37,   40,   53,
      517,   41,   38,   37,   59,   74,   74,   46,   87,    8,
       21,   46,   21,   21,   21,   21,   21,   21,   39,   79,
       39,   44,   44,   77,   46,   21,  289,  122,   21,   39,
       50,   44,   76,   21,   44,  122,   79,   76,   21,   21,
       90,   53,   59,  140,   79,   77,   21,   90,  140,   21,
       87,  146,  146,  118,  113,   21,  515,   60,   60,   60,
       60,  113,   76,   21,  289,   46,   21,   22,  118,   22,
       22,   22,   22,   22,   22,  514,   34,   34,   34,  166,
      166,  115,   34,   60,   34,   22,   34,  513,   34,   34,

       22,  115,  115,  143,  144,   22,   34,   73,  143,   73,
       73,   73,   73,   73,   73,  123,   22,  123,   60,  142,
      142,   60,   22,  285,  175,   73,  144,  182,  182,  168,
       22,   55,   55,  143,   55,   75,  168,   75,   55,  175,
       75,   75,   75,   75,   75,   75,   73,   55,   55,   55,
       55,   98,   98,   98,   98,   98,   98,  149,   55,   98,
      176,  145,   98,  512,  142,  285,  219,   98,   98,  176,
       98,  230,  226,   55,  128,  394,   55,  396,  145,  511,
       55,   55,  149,  508,  227,   55,  145,  128,  128,  128,
      128,  219,   55,  230,  507,   55,  226,   55,   55,   55,

      133,   55,   67,   67,   67,   67,   67,   67,  227,  133,
      133,  133,  133,  504,  501,  396,  128,  394,   67,   67,
      137,  500,  137,   67,  499,  137,  137,  137,  137,  137,
      137,  147,  147,  147,  147,  147,  147,  154,  133,   67,
       67,  295,  228,  498,  497,   67,   72,  228,   72,   72,
       72,   72,   72,   72,  148,  148,  148,  148,  148,  148,
      154,  479,  154,  207,   72,  154,  295,  479,  371,   72,
      231,  148,  228,  371,   72,  148,  207,  207,  207,  207,
      496,  495,  154,  494,  493,   72,  154,  231,  492,  491,
      154,   72,  148,  490,  489,  231,  488,  148,  487,   72,

      211,  486,  481,  478,  477,  207,  210,  476,  472,  211,
      211,  211,  211,  215,  215,  215,  215,  215,  215,  210,
      210,  210,  210,  210,  210,  297,  297,  297,  297,  297,
      297,  210,  210,  210,  210,  210,  210,  229,  211,  229,
      471,  470,  229,  229,  229,  229,  229,  229,  210,  469,
      467,  466,  210,  210,  210,  210,  210,  210,  214,  465,
      464,  462,  461,  460,  459,  457,  449,  214,  214,  214,
      214,  214,  214,  216,  216,  216,  216,  216,  216,  214,
      214,  214,  214,  214,  214,  448,  447,  446,  445,  444,
      216,  443,  442,  441,  216,  440,  214,  439,  438,  437,

      214,  214,  214,  214,  214,  214,  436,  435,  434,  428,
      427,  216,  425,  424,  421,  420,  216,  298,  298,  298,
      298,  298,  298,  419,  418,  417,  416,  413,  412,  411,
      410,  409,  407,  406,  298,  404,  403,  402,  298,  401,
      400,  399,  397,  392,  391,  390,  384,  383,  381,  378,
      377,  376,  375,  374,  373,  298,  372,  370,  369,  368,
      298,  520,  367,  520,  520,  520,  520,  520,  520,  520,
      521,  366,  521,  365,  521,  521,  521,  521,  521,  522,
      522,  522,  522,  523,  523,  364,  523,  363,  362,  523,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  525,

      361,  525,  525,  525,  525,  525,  525,  525,  526,  526,
      526,  527,  527,  528,  528,  529,  529,  530,  530,  531,
      531,  532,  532,  533,  533,  534,  534,  535,  535,  536,
      536,  537,  537,  538,  538,  539,  539,  540,  540,  541,
      541,  542,  542,  543,  543,  544,  544,  545,  545,  546,
      546,  547,  547,  548,  548,  549,  549,  550,  550,  551,
      551,  360,  359,  358,  357,  356,  355,  354,  345,  344,
      342,  341,  340,  339,  338,  336,  335,  334,  333,  332,
      330,  329,  328,  327,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  309,

      308,  307,  306,  305,  304,  302,  301,  300,  299,  284,
      283,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  269,  268,  267,  266,  263,  262,  261,  260,
      257,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  222,  221,  218,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  190,  189,  188,  187,  186,  185,  184,
      183,  181,  180,  179,  178,  174,  173,  172,  171,  170,
      169,  167,  165,  164,  163,  162,  161,  160,  159,  158,

      157,  152,  151,  141,  139,  127,  124,  121,  120,  119,
      117,  116,  114,  111,  110,  109,  108,  107,  106,  105,
      104,  103,  102,  101,  100,   99,   97,   96,   95,   94,
       93,   92,   91,   88,   85,   81,   78,   69,   68,   48,
       47,   45,   43,   42,   36,   33,   26,   15,   12,   10,
        7,    3,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main.l"
#line 2 "main.l"
#include<stdio.h>
#include<ctype.h>
char* rebuild_string(char* str) {
    int size=strlen(str);
    int i=0;
    char* result=(char*)malloc(size*2+1);
    int result_index=0;
    for(int i=0;i<size;i++){
        if(str[i]=='$'){
            result[result_index++]='$';
            result[result_index++]='$';
        } else if(str[i]=='\n'){
            result[result_index++]='$';
            result[result_index++]='n';
        } else if(str[i]=='\r'){
            result[result_index++]='$';
            result[result_index++]='r';
        } else if(str[i]=='\t'){
            result[result_index++]='$';
            result[result_index++]='t';
        } else if(str[i]=='\0'){
            result[result_index++]='$';
            result[result_index++]='0';
        }
        else if (str[i] == ' '){
            result[result_index++]='$';
            result[result_index++]='_';
        }
        else{
            result[result_index++]=str[i];
        }
    }
    result[result_index]='\0';
    return result;
}

#line 864 "lex.yy.c"
#line 865 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 80 "main.l"

#line 1084 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 520 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 853 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 81 "main.l"
{ char* res=rebuild_string(yytext); printf("comment\tLineComment\t%s\n", res); free(res); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 82 "main.l"
{ char* res=rebuild_string(yytext); printf("comment\tBlockComment\t%s\n", res); free(res); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 83 "main.l"
{ char* res=rebuild_string(yytext); printf("constant\tStringConst\t%s\n", res); free(res); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 84 "main.l"
{ printf("constant\tCharacterConst\t%s\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "main.l"
{ printf("constant\tFloatingConst\t%s\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 86 "main.l"
{ printf("constant\tIntegerConst\t%s\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 87 "main.l"
{ printf("keyword\tBreak\t%s\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "main.l"
{ printf("keyword\tCase\t%s\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 89 "main.l"
{ printf("keyword\tContinue\t%s\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 90 "main.l"
{ printf("keyword\tDefault\t%s\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 91 "main.l"
{ printf("keyword\tDo\t%s\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 92 "main.l"
{ printf("keyword\tElse\t%s\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 93 "main.l"
{ printf("keyword\tFor\t%s\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 94 "main.l"
{ printf("keyword\tIf\t%s\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 95 "main.l"
{ printf("keyword\tReturn\t%s\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 96 "main.l"
{ printf("keyword\tSwitch\t%s\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 97 "main.l"
{ printf("keyword\tWhile\t%s\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 98 "main.l"
{ printf("keyword\tUAlignas\t%s\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 99 "main.l"
{ printf("keyword\tUGeneric\t%s\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 100 "main.l"
{ printf("keyword\tUStaticAssert\t%s\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 101 "main.l"
{ printf("keyword\tUBVA\t%s\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 102 "main.l"
{ printf("keyword\tUBO\t%s\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 103 "main.l"
{ printf("keyword\tUAsm\t%s\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 104 "main.l"
{ printf("keyword\tUFortran\t%s\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 105 "main.l"
{ printf("keyword\tUAsm\t%s\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 106 "main.l"
{ printf("keyword\tUAsm\t%s\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 108 "main.l"
{ printf("operator\tArrow\t%s\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 109 "main.l"
{ printf("operator\tInc\t%s\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 110 "main.l"
{ printf("operator\tDec\t%s\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 111 "main.l"
{ printf("operator\tLShiftAssign\t%s\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 112 "main.l"
{ printf("operator\tRShiftAssign\t%s\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 113 "main.l"
{ printf("operator\tPlusAssign\t%s\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 114 "main.l"
{ printf("operator\tMinusAssign\t%s\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 115 "main.l"
{ printf("operator\tStarAssign\t%s\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 116 "main.l"
{ printf("operator\tSlashAssign\t%s\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 117 "main.l"
{ printf("operator\tPercentAssign\t%s\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 118 "main.l"
{ printf("operator\tAmpAssign\t%s\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 119 "main.l"
{ printf("operator\tBiterAssign\t%s\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 120 "main.l"
{ printf("operator\tCaretAssign\t%s\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 121 "main.l"
{ printf("operator\tEq\t%s\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 122 "main.l"
{ printf("operator\tNe\t%s\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 123 "main.l"
{ printf("operator\tLe\t%s\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 124 "main.l"
{ printf("operator\tGe\t%s\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 125 "main.l"
{ printf("operator\tLShift\t%s\n", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 126 "main.l"
{ printf("operator\tRShift\t%s\n", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 127 "main.l"
{ printf("operator\tAnd\t%s\n", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 128 "main.l"
{ printf("operator\tOr\t%s\n", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 130 "main.l"
{ printf("separator\tLParen\t%s\n", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 131 "main.l"
{ printf("separator\tRParen\t%s\n", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 132 "main.l"
{ printf("separator\tLBrace\t%s\n", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 133 "main.l"
{ printf("separator\tRBrace\t%s\n", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 134 "main.l"
{ printf("separator\tLBracket\t%s\n", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 135 "main.l"
{ printf("separator\tRBracket\t%s\n", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 136 "main.l"
{ printf("separator\tComma\t%s\n", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 137 "main.l"
{ printf("separator\tDot\t%s\n", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 139 "main.l"
{ printf("operator\tPos\t%s\n", yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 140 "main.l"
{ printf("operator\tneg\t%s\n", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 141 "main.l"
{ printf("operator\tStar\t%s\n", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 142 "main.l"
{ printf("operator\tSlash\t%s\n", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 143 "main.l"
{ printf("operator\tPercent\t%s\n", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 144 "main.l"
{ printf("operator\tAmp\t%s\n", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 145 "main.l"
{ printf("operator\tBiter\t%s\n", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 146 "main.l"
{ printf("operator\tCaret\t%s\n", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 147 "main.l"
{ printf("operator\tExclam\t%s\n", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 148 "main.l"
{ printf("operator\tQuestion\t%s\n", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 149 "main.l"
{ printf("operator\tColon\t%s\n", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 150 "main.l"
{ printf("operator\tAssign\t%s\n", yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 151 "main.l"
{ printf("operator\tLt\t%s\n", yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 152 "main.l"
{ printf("operator\tGt\t%s\n", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 153 "main.l"
{ printf("operator\tHash\t%s\n", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 154 "main.l"
{ printf("operator\tSingleQuote\t%s\n", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 155 "main.l"
{ printf("operator\tDoubleQuote\t%s\n", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 157 "main.l"
{ printf("delimiter\tDelimiter\t%s\n", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 159 "main.l"
{ printf("declarator\tSigned\t%s\n", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 160 "main.l"
{ printf("declarator\tUnsigned\t%s\n", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 162 "main.l"
{ printf("declarator\tAuto\t%s\n", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 163 "main.l"
{ printf("declarator\tStatic\t%s\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 164 "main.l"
{ printf("declarator\tExtern\t%s\n", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 165 "main.l"
{ printf("declarator\tRegister\t%s\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 166 "main.l"
{ printf("declarator\tUThreadULocal\t%s\n", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 167 "main.l"
{ printf("declarator\tTypedef\t%s\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 169 "main.l"
{ printf("declarator\tVoid\t%s\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 170 "main.l"
{ printf("declarator\tChar\t%s\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 171 "main.l"
{ printf("declarator\tShort\t%s\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 172 "main.l"
{ printf("declarator\tInt\t%s\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 173 "main.l"
{ printf("declarator\tLong\t%s\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 174 "main.l"
{ printf("declarator\tFloat\t%s\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 175 "main.l"
{ printf("declarator\tDouble\t%s\n", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 176 "main.l"
{ printf("declarator\tUBool\t%s\n", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 177 "main.l"
{ printf("declarator\tUComplex\t%s\n", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 178 "main.l"
{ printf("declarator\tUImaginary\t%s\n", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 179 "main.l"
{ printf("declarator\tUM128\t%s\n", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 180 "main.l"
{ printf("declarator\tUM128d\t%s\n", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 181 "main.l"
{ printf("declarator\tUM128i\t%s\n", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 183 "main.l"
{ printf("declarator\tStruct\t%s\n", yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 184 "main.l"
{ printf("declarator\tUnion\t%s\n", yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 185 "main.l"
{ printf("declarator\tEnum\t%s\n", yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 187 "main.l"
{ printf("declarator\tConst\t%s\n", yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 188 "main.l"
{ printf("declarator\tRestrict\t%s\n", yytext); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 189 "main.l"
{ printf("declarator\tVolatile\t%s\n", yytext); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 190 "main.l"
{ printf("declarator\tUVolatile\t%s\n", yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 191 "main.l"
{ printf("declarator\tUAtomic\t%s\n", yytext); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 193 "main.l"
{ printf("declarator\tInline\t%s\n", yytext); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 194 "main.l"
{ printf("declarator\tUInline\t%s\n", yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 195 "main.l"
{ printf("declarator\tUNoreturn\t%s\n", yytext); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 196 "main.l"
{ printf("declarator\tUStdcall\t%s\n", yytext); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 197 "main.l"
{ printf("declarator\tUCdecl\t%s\n", yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 198 "main.l"
{ printf("declarator\tUClrcall\t%s\n", yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 199 "main.l"
{ printf("declarator\tUFastcall\t%s\n", yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 200 "main.l"
{ printf("declarator\tUThiscall\t%s\n", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 201 "main.l"
{ printf("declarator\tUVectorcall\t%s\n", yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 203 "main.l"
{ printf("declarator\tUTypeof\t%s\n", yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 204 "main.l"
{ printf("declarator\tUExtension\t%s\n", yytext); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 205 "main.l"
{ printf("declarator\tUDeclspec\t%s\n", yytext); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 206 "main.l"
{ printf("declarator\tUAttribute\t%s\n", yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 208 "main.l"
{ printf("identifier\tIdentifier\t%s\n", yytext); }
	YY_BREAK
case 117:
/* rule 117 can match eol */
YY_RULE_SETUP
#line 210 "main.l"
;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 212 "main.l"
{ printf("unknown\tUnknown\t%s\n", yytext); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 214 "main.l"
ECHO;
	YY_BREAK
#line 1740 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 520 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 520 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 519);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 214 "main.l"

int main()
{
    printf("TYPE\tCATEGORY\tVALUE\n");
    yylex();
    return 0;
}
